cmake_minimum_required(VERSION 3.21)
project(toolchain_test)
include (CTest)

enable_language(CXX C ASM)

add_executable(c c.c)
add_executable(cpp cpp.cpp)
add_executable(s s.S)
add_executable(lowers lowers.S)
set(APPLICATIONS c cpp s lowers)

if(CMAKE_SYSTEM_PROCESSOR STREQUAL XCORE_XS2A OR
   CMAKE_SYSTEM_PROCESSOR STREQUAL XCORE_XS3A)
    add_executable(xc xc.xc)
    add_executable(ass ass.ass)
    list(APPEND APPLICATIONS xc ass)
endif()

message(STATUS "Building for CMAKE_SYSTEM_PROCESSOR : ${CMAKE_SYSTEM_PROCESSOR}")
set(EXTRA_ARGS "")
if(CMAKE_SYSTEM_PROCESSOR STREQUAL XCORE_XS2A)
    set(TARGET -target=XCORE-200-EXPLORER)
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL XCORE_XS3A)    
    set(TARGET -target=XK-EVK-XU316)
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL XCORE_VX4)
    set(TARGET -target=XK-EVK-XU416)
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL riscv32)
    set(TARGET "")
    set(EXTRA_ARGS --config-file ${CMAKE_CURRENT_LIST_DIR}/config.xml)
else()
    message(FATAL_ERROR "Unsupported CMAKE_SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}")
endif()

foreach(app IN LISTS APPLICATIONS)
    target_compile_options(${app} PRIVATE ${TARGET})
    target_link_options(${app} PRIVATE ${TARGET})
    add_test(NAME ${app} COMMAND xsim $<TARGET_FILE:${app}> ${EXTRA_ARGS})
endforeach()
