// Copyright 2023 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.

.text
.issue_mode single
.align 4

.cc_top main.function,main

main:
    entsp 0
    ldc r0, 0
    retsp 0


.L_func_end:
.cc_bottom main.function

.globl main
.type main,@function
.set main.nstackwords,0;  .global main.nstackwords
.set main.maxcores,1;               .global main.maxcores
.set main.maxtimers,0;              .global main.maxtimers
.set main.maxchanends,0;            .global main.maxchanends
